INVALID_REQUEST_BODY_PROPERTIES = "Invalid request body properties"
EMPTY_LINK = "Link is empty"
EMPTY_COLUMN = "Column is empty"
INVALID_LINK = "Invalid spreadsheet link format"
DATA_NOT_FOUND = "No data found in the specified range"
EMPTY_FEEDBACK_LIST = "No feedback provided for clustering"
